In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [3]:
# Loading dataset to a pandas dataframe
df=pd.read_csv('creditcard.csv')

In [9]:
# 5 random rowss of dataset
df.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

In [10]:
# dataset information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [11]:
# checking the no. of missing values in each column
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [12]:
# distribution of legit transcation and  fraudlent transc.
df['Class'].value_counts()

0    284315
1       492
Name: Class, dtype: int64

In [13]:
# So here we can see that legit transc are more than fraudlent one so whenever we give any test data it will predict it as. normal transc .
# This is unbalanced dataset and we cannot train our machine learning model in it
# 0    284315 (Normal Transc.)
# 1       492 (Fraud Transc.)

In [14]:
# Seprating the data for analysis
legit=df[df.Class==0]
fraud=df[df.Class==1]

In [17]:
fraud.shape

(492, 31)

In [18]:
# Satatical mearsure of the data
legit.Amount.describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [19]:
fraud.Amount.describe()

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [21]:
# Compare the values for both transc
df.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94838.202258,0.008258,-0.006271,0.012171,-0.007860,0.005453,0.002419,0.009637,-0.000987,0.004467,...,-0.000644,-0.001235,-0.000024,0.000070,0.000182,-0.000072,-0.000089,-0.000295,-0.000131,88.291022
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

In [22]:
# Under Sampling
# Build sample dataset containg similar distribution of legit transc. and fraud transc.

In [23]:
legitSample=legit.sample(n=492)

In [24]:
legitSample

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
112470,72660.0,1.076399,-0.236834,1.326728,0.744335,-0.916717,0.384935,-0.774604,0.325838,0.601097,...,0.006402,0.220779,0.067417,0.282247,0.135132,0.314615,0.031576,0.016992,11.50,0
22618,32344.0,1.260574,0.109461,0.059664,0.096582,-0.390486,-1.317197,0.317836,-0.298562,-0.007985,...,-0.436478,-1.377747,0.195202,0.390359,0.079682,0.621516,-0.107643,0.006464,27.99,0
82232,59312.0,-0.985385,0.127735,2.343602,1.689115,-1.392629,1.232577,1.267313,-0.069400,1.338320,...,-0.530780,-0.567480,0.163571,0.352373,-0.114466,-0.428707,0.309230,-0.244821,261.50,0
126920,78147.0,0.689604,-0.676754,-0.398769,0.577305,-0.269999,-0.634893,0.698537,-0.224375,-0.440045,...,-0.175475,-1.258120,-0.166832,0.009619,0.187082,0.109949,-0.125242,0.047499,303.90,0
70909,54071.0,1.146286,-0.358282,0.688945,0.382457,-1.016927,-0.711002,-0.300613,0.001004,0.960745,...,-0.377341,-1.116352,0.141288,0.379967,0.050295,0.528067,-0.060161,0.019243,53.21,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117170,74567.0,-0.585557,1.310272,1.198312,0.010049,0.042373,-1.002060,0.724617,-0.089626,-0.275733,...,-0.288198,-0.672163,-0.002106,0.343593,-0.090554,0.075059,0.353630,0.164477,4.45,0
54941,46694.0,0.082187,-1.642039,0.358387,1.440360,-0.912515,0.663564,0.155376,0.147812,0.029134,...,0.403870,-0.024800,-0.471403,-0.284866,0.077233,-0.458984,-0.033470,0.116375,544.55,0
250151,154753.0,-0.756284,-0.500967,1.149397,-1.191394,0.773842,0.304727,-0.150586,0.350263,0.317207,...,0.246980,0.433886,0.302982,0.116800,-1.040273,0.215911,0.136818,0.236022,77.50,0
85424,60765.0,-0.336502,0.912666,1.930708,2.904695,0.045819,0.907801,-0.063632,0.421495,-0.916061,...,-0.122904,-0.312064,0.200871,-0.033005,-1.168128,-0.162402,0.090500,0.211797,1.00,0
238425,149661.0,-3.841720,3.405097,-2.614096,-1.244508,-1.219199,-1.873810,-0.860238,2.000261,-0.036391,...,0.602337,0.684871,-0.055654,-0.084554,0.157520,-0.502968,-2.226550,-0.655661,3.84,0

In [25]:
# Concatenating two dataframe

In [26]:
newDF=pd.concat([legitSample,fraud],axis=0) # axis=0 (row wise)   and axis=1 (column wise)

In [27]:
newDF

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
112470,72660.0,1.076399,-0.236834,1.326728,0.744335,-0.916717,0.384935,-0.774604,0.325838,0.601097,...,0.006402,0.220779,0.067417,0.282247,0.135132,0.314615,0.031576,0.016992,11.50,0
22618,32344.0,1.260574,0.109461,0.059664,0.096582,-0.390486,-1.317197,0.317836,-0.298562,-0.007985,...,-0.436478,-1.377747,0.195202,0.390359,0.079682,0.621516,-0.107643,0.006464,27.99,0
82232,59312.0,-0.985385,0.127735,2.343602,1.689115,-1.392629,1.232577,1.267313,-0.069400,1.338320,...,-0.530780,-0.567480,0.163571,0.352373,-0.114466,-0.428707,0.309230,-0.244821,261.50,0
126920,78147.0,0.689604,-0.676754,-0.398769,0.577305,-0.269999,-0.634893,0.698537,-0.224375,-0.440045,...,-0.175475,-1.258120,-0.166832,0.009619,0.187082,0.109949,-0.125242,0.047499,303.90,0
70909,54071.0,1.146286,-0.358282,0.688945,0.382457,-1.016927,-0.711002,-0.300613,0.001004,0.960745,...,-0.377341,-1.116352,0.141288,0.379967,0.050295,0.528067,-0.060161,0.019243,53.21,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279863,169142.0,-1.927883,1.125653,-4.518331,1.749293,-1.566487,-2.010494,-0.882850,0.697211,-2.064945,...,0.778584,-0.319189,0.639419,-0.294885,0.537503,0.788395,0.292680,0.147968,390.00,1
280143,169347.0,1.378559,1.289381,-5.004247,1.411850,0.442581,-1.326536,-1.413170,0.248525,-1.127396,...,0.370612,0.028234,-0.145640,-0.081049,0.521875,0.739467,0.389152,0.186637,0.76,1
280149,169351.0,-0.676143,1.126366,-2.213700,0.468308,-1.120541,-0.003346,-2.234739,1.210158,-0.652250,...,0.751826,0.834108,0.190944,0.032070,-0.739695,0.471111,0.385107,0.194361,77.89,1
281144,169966.0,-3.113832,0.585864,-5.399730,1.817092,-0.840618,-2.943548,-2.208002,1.058733,-1.632333,...,0.583276,-0.269209,-0.456108,-0.183659,-0.328168,0.606116,0.884876,-0.253700,245.00,1
281674,170348.0,1.991976,0.158476,-2.583441,0.408670,1.151147,-0.096695,0.223050,-0.068384,0.577829,...,-0.164350,-0.295135,-0.072173,-0.450261,0.313267,-0.289617,0.002988,-0.015309,42.53,1

In [29]:
newDF['Class'].value_counts()

0    492
1    492
Name: Class, dtype: int64

In [30]:
newDF.groupby("Class").mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,97017.565041,0.086461,-0.035076,0.027259,0.064887,0.058205,-0.005131,0.058032,0.072837,0.007797,...,0.011319,0.012192,-0.004446,-0.004827,-0.011717,-0.020942,0.003325,0.009215,-0.012297,91.504512
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

In [31]:
# Splitting the data into features and targets

In [36]:
X=newDF.drop(columns='Class',axis=1)
y=newDF['Class']

In [33]:
X

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
112470,72660.0,1.076399,-0.236834,1.326728,0.744335,-0.916717,0.384935,-0.774604,0.325838,0.601097,...,-0.100469,0.006402,0.220779,0.067417,0.282247,0.135132,0.314615,0.031576,0.016992,11.50
22618,32344.0,1.260574,0.109461,0.059664,0.096582,-0.390486,-1.317197,0.317836,-0.298562,-0.007985,...,-0.058157,-0.436478,-1.377747,0.195202,0.390359,0.079682,0.621516,-0.107643,0.006464,27.99
82232,59312.0,-0.985385,0.127735,2.343602,1.689115,-1.392629,1.232577,1.267313,-0.069400,1.338320,...,0.293980,-0.530780,-0.567480,0.163571,0.352373,-0.114466,-0.428707,0.309230,-0.244821,261.50
126920,78147.0,0.689604,-0.676754,-0.398769,0.577305,-0.269999,-0.634893,0.698537,-0.224375,-0.440045,...,0.516328,-0.175475,-1.258120,-0.166832,0.009619,0.187082,0.109949,-0.125242,0.047499,303.90
70909,54071.0,1.146286,-0.358282,0.688945,0.382457,-1.016927,-0.711002,-0.300613,0.001004,0.960745,...,-0.094525,-0.377341,-1.116352,0.141288,0.379967,0.050295,0.528067,-0.060161,0.019243,53.21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279863,169142.0,-1.927883,1.125653,-4.518331,1.749293,-1.566487,-2.010494,-0.882850,0.697211,-2.064945,...,1.252967,0.778584,-0.319189,0.639419,-0.294885,0.537503,0.788395,0.292680,0.147968,390.00
280143,169347.0,1.378559,1.289381,-5.004247,1.411850,0.442581,-1.326536,-1.413170,0.248525,-1.127396,...,0.226138,0.370612,0.028234,-0.145640,-0.081049,0.521875,0.739467,0.389152,0.186637,0.76
280149,169351.0,-0.676143,1.126366,-2.213700,0.468308,-1.120541,-0.003346,-2.234739,1.210158,-0.652250,...,0.247968,0.751826,0.834108,0.190944,0.032070,-0.739695,0.471111,0.385107,0.194361,77.89
281144,169966.0,-3.113832,0.585864,-5.399730,1.817092,-0.840618,-2.943548,-2.208002,1.058733,-1.632333,...,0.306271,0.583276,-0.269209,-0.456108,-0.183659,-0.328168,0.606116,0.884876,-0.253700,245.00
281674,170348.0,1.991976,0.158476,-2.583441,0.408670,1.151147,-0.096695,0.223050,-0.068384,0.577829,...,-0.017652,-0.164350,-0.295135,-0.072173,-0.450261,0.313267,-0.289617,0.002988,-0.015309,42.53

In [37]:
y

112470    0
22618     0
82232     0
126920    0
70909     0
         ..
279863    1
280143    1
280149    1
281144    1
281674    1
Name: Class, Length: 984, dtype: int64

In [38]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.2,stratify=y,random_state= 2)

In [39]:
X_train.shape

(787, 30)

In [40]:
X_test.shape

(197, 30)

In [41]:
# Model Training

In [42]:
model=LogisticRegression()

In [43]:
# Training the data in lr model with training data
model.fit(X_train,y_train)

LogisticRegression()

In [44]:
# Evaluation 
# Accuracy score

In [46]:
# Accuracy on training data
xTrainPred=model.predict(X_train)
trainingAcc=accuracy_score(xTrainPred,y_train)

In [47]:
trainingAcc

0.9428208386277002

In [51]:
xTestPred=model.predict(X_test)
testingAcc=accuracy_score(xTestPred,y_test)

In [52]:
testingAcc

0.9238578680203046

In [ ]:
cc